services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: iip_secure_stack-app
    ports:
      - "127.0.0.1:5001:5001"

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    image: iip_secure_stack-bff

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: iip_secure_stack-nginx

  webhook:
    build:
      context: ./webhook
      dockerfile: Dockerfile
    image: iip_secure_stack-webhook
