apiVersion: v1
kind: Pod
metadata:
  name: lr-check
  namespace: iip-dev
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: lr-check
    image: busybox:stable
    args: ["sleep","300"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["NET_RAW","ALL"]   # <-- NET_RAW first to satisfy the policy
