apiVersion: v1
kind: Pod
metadata:
  name: kyverno-deny-test
  namespace: iip-dev
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: c
    image: busybox@sha256:355b3a1bf5609da364166913878a8508d4ba30572d02020a97028c75477e24ff
    command: ["sh","-c","sleep 3600"]
