name: ci
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - run: |
          python -m pip install -U pip
          pip install -r app/requirements.txt -r app/requirements-dev.txt
          cd app
          pytest -q
          black --check .
          ruff check .
          isort --check-only .
          mypy . || true
          bandit -q -r .
          pip-audit || true
  docker_build_and_scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t iip-secure-stack:ci app
      - name: Trivy scan image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: iip-secure-stack:ci
          format: table
          exit-code: '0'
          ignore-unfixed: true
